site_name: HTW P2P Volltextsuche
site_description: 'Dokumentation für das Projektstudium'
site_author: 'Boris Caspary, Emma Calewaert, Jonathan Neidel, Joscha Seelig, Leon Enzenberger, Ryan Torzynski, Simon Breiter, Stefan Sadewasser'
site_url: https://htw-projekt-p2p-volltextsuche.github.io/docs/
docs_dir: docs/
repo_name: 'htw-projekt-p2p-volltextsuche/docs'
repo_url: 'https://github.com/htw-projekt-p2p-volltextsuche/docs'
plugins:
 - search
 - with-pdf
nav:
  - Home: 
    - Credits: home/index.md
    - Basic concepts: home/basic_concepts.md
    - Subject: home/subject.md
    - Work division: home/work_division.md
  - Design decisions:
    - About: design_decisions/about.md
    - Architecture Diagram: design_decisions/architecture_diagram.md
    - Speech Handling Diagrams: design_decisions/speech_handling_diagrams.md
    - Partition by Keyword: design_decisions/partition_by_keyword.md
  - Text Processing: 
    - Crawler:
      - Über: crawler/about.md
      - Installation: crawler/installation.md
    - Textextraction 19:
      - Über: textextraction-19/about.md
      - Titel der Reden: textextraction-19/titel_der_reden.md
      - Nutzung: textextraction-19/nutzung.md
      - Anforderungen: textextraction-19/anforderungen.md
      - Format der zurückgegebenen JSON-Datei: textextraction-19/format.md
    - Textextraction 18:
      - About: textextraction-18/textextraction-18.md
      - Problems: textextraction-18/problems.md
      - Build Jar File: textextraction-18/build_jar_file.md
      - Execute: textextraction-18/execute.md
  - Fulltext-search:
    - P2P-DHT:
      - About: p2p-dht/about.md
      - Design: p2p-dht/design.md
      - Run: p2p-dht/run.md
      - Configure: p2p-dht/configure.md
      - Scripts: p2p-dht/scripts.md
    - Fulltext-search:
      - About: fulltext-search/about.md
      - Get Started: fulltext-search/get_started.md
      - Retrieve search results: fulltext-search/retrieve_search_results.md
  - User Interface:
    - Problemstellung: user_interface/problemstellung.md
    - Lösungsansatz: user_interface/lösungsansatz.md
    - Probleme: user_interface/probleme.md
    - Schlussbetrachtung: user_interface/schlussbetrachtung.md
    - Verwendung der Software: user_interface/verwendung_der_software.md
  - OPS:
    - About: ops/about.md
    - Setup: ops/setup.md
    - Challenges: ops/challenges.md
  - Outlook:
    - About: outlook/about.md

theme:
  name: 'material'

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.annotate
    - content.tabs.link
    # - header.autohide
    # - navigation.expand
    # - navigation.indexes
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate